fix: `packageDefinitions` in `lib.nix`
realized that i couldn't use a function the way i currently was. decided
to go the super simple and obvious route that i previously overlooked.
just define some attribute sets and reuse them with inherit whenever
possible and then add to a set to customize it for a package with the
`//` operator. this is even better than what i was trying to achieve
before and it actually works correctly because my last approach was
actually broken without me even realizing it since i didn't do `nix
flake check`. basically the packages were broken and i kept getting
`error: attempt to call something which is not a function but a set`